stages:
 stage_01:
   cmd: python stage_01.py
   deps:
   - stage_01.py
   outs:
   - artifacts01.txt

 stage_02:
   cmd: python stage_02.py
   deps:
   - stage_02.py
   - artifacts01.txt

 stage_03:
   cmd: python stage_03.py
   deps:
   - stage_03.py
   - artifacts01.txt
   outs:
   - artifacts02.txt

