stages:
 stage_01:
   cmd: python stage_01.py
   deps:
   - stage_01.py
   outs:
   - artifactory.txt

 stage_02:
   cmd: python stage_02.py
   deps:
   - stage_02.py
   - artifactory.txt                                            
